name: 关于安装系统的建议
description: 关于安装系统的 UI、操作、指令等的任何建议。
labels: ["Installer","Advice"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        我们将认真对待任何用户提出的有意义建议。感谢您的建议。
  - type: textarea
    id: advice
    attributes:
      label: 修改建议
      description: 请描述修改的目标模式，最好附上修改方法。
    validations:
      required: true